import cv2
import matplotlib.pyplot as plt
#The rest of your code remains the same
image = cv2.imread('glass.jpg')
hsv_image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
lower_red1 = np.array([0, 120, 70])
upper_red1 = np.array([10, 255, 255])
lower_red2 = np.array([170, 120, 70])
upper_red2 = np.array([180, 255, 255])
lower_blue = np.array([100, 150, 70])
upper_blue = np.array([140, 255, 255])
lower_green = np.array([40, 70, 70])
upper_green = np.array([80, 255, 255])
mask_red1 = cv2.inRange(hsv_image, lower_red1, upper_red1)
mask_red2 = cv2.inRange(hsv_image, lower_red2, upper_red2)
mask_red = cv2.add(mask_red1, mask_red2) # Combine both masks for red
mask_blue = cv2.inRange(hsv_image, lower_blue, upper_blue)
mask_green = cv2.inRange(hsv_image, lower_green, upper_green)
red_objects = cv2.bitwise_and(image, image, mask=mask_red)
blue_objects = cv2.bitwise_and(image, image, mask=mask_blue)
green_objects = cv2.bitwise_and(image, image, mask=mask_green)
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
red_objects_rgb = cv2.cvtColor(red_objects, cv2.COLOR_BGR2RGB)
blue_objects_rgb = cv2.cvtColor(blue_objects, cv2.COLOR_BGR2RGB)
green_objects_rgb = cv2.cvtColor(green_objects, cv2.COLOR_BGR2RGB)
plt.figure(figsize=(10, 10))
plt.subplot(2, 2, 1)
plt.imshow(image_rgb)
plt.title('Original Image')
plt.axis('off')
plt.subplot(2, 2, 2)
plt.imshow(red_objects_rgb)
plt.title('Red Objects')
plt.axis('off')
plt.subplot(2, 2, 3)
plt.imshow(blue_objects_rgb)
plt.title('Blue Objects')
plt.axis('off')
plt.subplot(2, 2, 4)
plt.imshow(green_objects_rgb)
plt.title('Green Objects')
plt.axis('off')
plt.tight_layout()
plt.show()
